name: sync-to-atomgit

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          ref: main

      - name: Set git user
        run: |
          git config --global user.name "xiaojunnuo"
          git config --global user.email "xiaojunnuo@qq.com"

      - name: Push to atomgit
        run: |
          git remote add atomgit https://greper:${{ secrets.ATOMGIT_TOKEN }}@atomgit.com/certd/jks-go
          git push --set-upstream atomgit main --tags
